# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          publish_dir: ./public # 이 폴더에 있는 파일을 배포